#!/bin/bash
#SBATCH -J dlrbnicsx_saddle_point
#SBATCH -A WELLS-SL3-CPU
#SBATCH --output=test_job_%A_%a.out
#SBATCH --error=test_job_%A_%a.err

#SBATCH --nodes=1
#SBATCH --ntasks=4
#SBATCH --time=00:30:00
#SBATCH --mem=42000mb

#SBATCH -p icelake-himem
#SBATCH --mail-type=ALL

module purge
source ../../../fenics_branch/share/spack/setup-env.sh
spack env activate fenicsx-env
spack env status
spack load py-pip@23.1.2
spack clean
# cd mesh_data
# mpiexec -n 1 python3 mesh.py
cd ..
/usr/bin/time -v mpiexec -n 4 python3 dlrbnicsx_saddle_point_distributed.py
